@startuml

title __STUDENTS's Class Diagram__\n

  namespace  {
    namespace odel {
      namespace students {
        class model.students.Student {
            - _class : String
            - id : int
            - isExchange : boolean
            - name : String
            - semester : int
            + Student()
            + equals()
            + getId()
            + getName()
            + getSemester()
            + get_class()
            + hashCode()
            + isExchange()
            + setExchange()
            + setId()
            + setName()
            + setSemester()
            + set_class()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace students {
        class model.students.StudentList {
            - studentList : ArrayList<Student>
            + StudentList()
            + StudentList()
            + addStudent()
            + copy()
            + getExchangeStudents()
            + getStudent()
            + getStudentList()
            + getStudentsByClass()
            + getStudentsByName()
            + readStudentFromTXTFile()
            + readStudentListFromBinFile()
            + removeStudent()
            + setStudentList()
            + toString()
            + writeStudentListToBinFile()
            - isValidStudent()
        }
      }
    }
  }
  

  model.students.Student .up.|> java.io.Serializable
  model.students.StudentList .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
