@startuml

title __ROOMS's Class Diagram__\n

  namespace  {
    namespace odel {
      namespace rooms {
        class model.rooms.BookingTime {
            - bookingEnd : LocalTime
            - bookingStart : LocalTime
            - date : LocalDate
            + BookingTime()
            + collideWith()
            + equals()
            + getBookingEnd()
            + getBookingStart()
            + getDate()
            + hashCode()
            + setBookingEnd()
            + setBookingStart()
            + setDate()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace rooms {
        class model.rooms.Room {
            - capacity : int
            - intervals : ArrayList<BookingTime>
            - mergeWith : String
            - name : String
            + Book()
            + Room()
            + canBeBookedAt()
            + getCapacity()
            + getIntervals()
            + getMergeWith()
            + getName()
            + setCapacity()
            + setIntervals()
            + setMergeWith()
            + setName()
            + toString()
            + unBook()
        }
      }
    }
  }
  

  namespace  {
    namespace odel {
      namespace rooms {
        class model.rooms.RoomList {
            - rooms : ArrayList<Room>
            + RoomList()
            + addRoom()
            + getAvailableRoomsAt()
            + getRooms()
            + readRoomsFromTXTFile()
            + readRoomsListFromBinFile()
            + removeRoom()
            + setRooms()
            + toString()
            + writeRoomListToBinFile()
        }
      }
    }
  }
  

  model.rooms.BookingTime .up.|> java.io.Serializable
  model.rooms.Room .up.|> java.io.Serializable
  model.rooms.RoomList .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
