@startuml

title __CALENDAR's Class Diagram__\n

    namespace Model {
      namespace calendar {
        class model.calendar.Day {
            - date : LocalDate
            - lessons : ArrayList<Lesson>
            + addLesson()
            + getIndexForDay()
            + getLessons()
            + removeLesson()
            + setDate()
            + setLessons()
            + sortLessons()
            + toString()
        }
      }
    }
  

    namespace Model {
      namespace calendar {
        class model.calendar.Lesson {
            - course : String
            - end : LocalTime
            - start : LocalTime
            + Lesson()
            + equals()
            + getCourse()
            + getEnd()
            + getStart()
            + hashCode()
            + setCourse()
            + setEnd()
            + setStart()
            + setTime()
            + toString()
        }
      }
    }

  

    namespace Model {
      namespace calendar {
        class model.calendar.Semester {
            - currentWeekIndex : int
            - numberOfWeeksInSemester : int
            - semesterEnd : LocalDate
            - semesterStart : LocalDate
            - weekList : ArrayList<Week>
            + Semester()
            + getCurrentWeek()
            + getCurrentWeekIndex()
            + getCurrentYear()
            + getNumberOfWeeksBetween()
            + getWeekList()
            + goNextWeek()
            + goPreviousWeek()
            + hasNextWeek()
            + hasPreviousWeek()
            + initializeAllWeeks()
            + initializeCurrentWeekIndex()
            + readData()
            + saveData()
            + toString()
        }
      }
    }

  

    namespace Model {
      namespace calendar {
        class model.calendar.Week {
            - days : Day[]
            - end : LocalDate
            - start : LocalDate
            + Week()
            + addLesson()
            + getDays()
            + getEnd()
            + getStart()
            + toString()
        }
      }
    }

  

  model.calendar.Day .up.|> java.io.Serializable
  model.calendar.Lesson .up.|> java.io.Serializable
  model.calendar.Week .up.|> java.io.Serializable
  model.calendar.Week .-- model.calendar.Semester
  model.calendar.Lesson .-- model.calendar.Semester
  model.calendar.Day .-- model.calendar.Semester


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
