@startuml

title __MODEL's Class Diagram__\n


    namespace odel {
      class model.Calendar {
      }
    }

  

    namespace odel {
      class model.Class {
          - name : String
          - studentlist: Studentlist
          + Class()
          + getName()
          + getStudentList()
          + getStudentsList()
          + setName()
          + toString()
      }
    }

  


    namespace odel {
      class model.Course {
          - title : String
          + Course()
          + Course()
          + getClassOfStudents()
          + getParticipants()
          + getTeacherList()
          + getTitle()
          + initStudents()
          + setClassOfStudents()
          + setParticipants()
          + setTeacherList()
          + setTitle()
          + toString()
      }
    }

  


    namespace odel {
      class model.CourseList {
          - courses : ArrayList<Course>
          + CourseList()
          + addCourse()
          + getCourses()
          + getCoursesByClass()
          + getCoursesByClassName()
          + getCoursesByTeachers()
          + getCoursesByTitle()
          + importCourses()
          + readCourseListFromBinFile()
          + removeCourse()
          + writeCourseListToBinFile()
      }
    }

  


    namespace odel {
      class model.CourseTest {
          {static} + main()
      }
    }

  


    namespace odel {
      class model.Day {
          - date : LocalDate
          - lessons : ArrayList<Lesson>
          + addLesson()
          + getIndexForDay()
          + getLessons()
          + removeLesson()
          + setDate()
          + setLessons()
          + sortLessons()
          + toString()
      }
    }

  

    namespace odel {
      class model.Lesson {
          - course : String
          - end : LocalTime
          - start : LocalTime
          + Lesson()
          + equals()
          + getCourse()
          + getEnd()
          + getStart()
          + hashCode()
          + setCourse()
          + setEnd()
          + setStart()
          + setTime()
          + toString()
      }
    }

  


    namespace odel {
      interface model.Model {
          {abstract} + getCurrentWeek()
          {abstract} + getCurrentWeekIndex()
          {abstract} + getCurrentYear()
          {abstract} + getNumberOfWeeksBetween()
          {abstract} + getWeekList()
          {abstract} + goNextWeek()
          {abstract} + goPreviousWeek()
          {abstract} + initializeAllWeeks()
          {abstract} + initializeCurrentWeekIndex()
          {abstract} + readStudentFromTXTFile()
      }
    }

  


    namespace odel {
      class model.ModelManager {
          + ModelManager()
          + getCurrentWeek()
          + getCurrentWeekIndex()
          + getCurrentYear()
          + getNumberOfWeeksBetween()
          + getWeekList()
          + goNextWeek()
          + goPreviousWeek()
          + initializeAllWeeks()
          + initializeCurrentWeekIndex()
          + readStudentFromTXTFile()
          + setSemester()
      }
    }

  


    namespace odel {
      class model.Semester {
          - currentWeekIndex : int
          - numberOfWeeksInSemester : int
          - semesterEnd : LocalDate
          - semesterStart : LocalDate
          - weekList : ArrayList<Week>
          + Semester()
          + getCurrentWeek()
          + getCurrentWeekIndex()
          + getCurrentYear()
          + getNumberOfWeeksBetween()
          + getWeekList()
          + goNextWeek()
          + goPreviousWeek()
          + initializeAllWeeks()
          + initializeCurrentWeekIndex()
          + readData()
          + saveData()
          + toString()
      }
    }

  


    namespace odel {
      class model.Student {
          - _class : String
          - id : int
          - isExchange : boolean
          - name : String
          - semester : int
          + Student()
          + equals()
          + getId()
          + getName()
          + getSemester()
          + get_class()
          + hashCode()
          + isExchange()
          + setExchange()
          + setId()
          + setName()
          + setSemester()
          + set_class()
          + toString()
      }
    }

  


    namespace odel {
      class model.StudentList {
          - studentList : ArrayList<Student>
          + StudentList()
          + StudentList()
          + addStudent()
          + copy()
          + getExchangeStudents()
          + getStudent()
          + getStudentList()
          + getStudentsByClass()
          + getStudentsByName()
          + readStudentFromTXTFile()
          + readStudentListFromBinFile()
          + removeStudent()
          + setStudentList()
          + toString()
          + writeStudentListToBinFile()
          - isValidStudent()
      }
    }

  


    namespace odel {
      class model.Teacher {
      }
    }

  


    namespace odel {
      class model.TeacherList {
          ~ teachers : ArrayList<Teacher>
          + TeacherList()
          + TeacherList()
          + addTeacher()
          + getTeacherByIndex()
          + removeTeacher()
          + size()
      }
    }

  


    namespace odel {
      class model.Week {
          - days : Day[]
          - end : LocalDate
          - start : LocalDate
          + Week()
          + addLesson()
          + getDays()
          + getEnd()
          + getStart()
          + toString()
      }
    }

  

  model.Class .up.|> java.io.Serializable
  model.Class o-- model.StudentList : studentList
  model.Course .up.|> java.io.Serializable
  model.Course o-- model.Class : classOfStudents
  model.Course o-- model.StudentList : participants
  model.Course o-- model.TeacherList : teacherList
  model.Day .up.|> java.io.Serializable
  model.Lesson .up.|> java.io.Serializable
  model.ModelManager .up.|> model.Model
  model.ModelManager o-- model.Semester : semester
  model.ModelManager o-- model.StudentList : studentList
  model.Student .up.|> java.io.Serializable
  model.StudentList .up.|> java.io.Serializable
  model.Teacher .up.|> java.io.Serializable
  model.TeacherList .up.|> java.io.Serializable
  model.Week .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
